services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d myappdb"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fastapi:
    build: .
    environment:
      # Updated DATABASE_URL to use the asyncpg driver
      DATABASE_URL: postgresql+asyncpg://user:password@postgres:5432/myappdb
    volumes:
      - ./:/myapp/
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  app-network:

volumes:
  postgres-data:
  pgadmin-data:
